"""
Name: James Reed
Date: 09/15/25
Assignment: 2
Due Date: 09/26/25
About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes) process log file using Combined Log Format(CLF)
Assumptions: assumes correct user input of file path and date format
All work below was performed solely by James
I [did not use] code generated by an AI tool.
"""

def main(logs, start_date, end_date):


if __name__ == "__main__":
    """FIND WETHER LOG FITS WITHIN THE SPECIFIED RANGE OF DATES"""
    