"""
Name: James Reed
Date: 09/15/25
Assignment: 2
Due Date: 09/26/25
About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes) process log file using Combined Log Format(CLF)
Assumptions: assumes correct user input of file path and date format
All work below was performed solely by James
I [did not use] code generated by an AI tool.
"""

import sys

def open_log_file(file_path):
    """Open and read the log file, returning its contents."""
    try:
        

if __name__ == "__main__":
    """FIND WETHER LOG FITS WITHIN THE SPECIFIED RANGE OF DATES"""
    # [0] is the python filename
    logFilePath = sys.argv[1] if len(sys.argv) > 1 else None
    start_date = sys.argv[2] if len(sys.argv) > 2 else "01/01/0000"
    end_date = sys.argv[3] if len(sys.argv) > 3 else "12/30/9999"

    print(logFilePath, start_date, end_date)