"""
Name: James Reed
Date: 09/11/2025
Assignment: 1
Due Date: 09/12/2025
About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes)
Assumptions: (write any assumptions made here (ex: assumes correct user input))
All work below was performed solely by (Your Name).
I [did not use | used] code generated by an AI tool.
"""

defect = 0      #false 
cooperate = 1   #true
myHistory = []  #past player choices
oppHistory = [] #past opponent choices
num_of_iterations = 2000    #default 2000
num_of_strategies = 8       #default 8

strategies = {
    "alwaysCooperate": 0,
    "alwaysDefect": 1,
    "strategy_probAndLock": 2
}

def rangeReward(beg, end, myHistory, oppHistory):
    """computes total rewards in the range of rounds from beg to end-1"""
    reward = 0
    for i in range(beg, end):
        reward = reward + myHistory[i] + oppHistory[i]
    return reward

def alwaysCooperate(myHistory, oppHistory):
    """always cooperates"""
    return cooperate

def alwaysDefect(myHistory, oppHistory):
    """always defects"""
    return defect

def strategy_probAndLock(myHistory, oppHistory):
    """Defect first 20, Cooperate second 20, till end choose higher yeilding option"""
    if (len(myHistory) < 20):
        return defect
    if (len(myHistory) < 40): 
        return cooperate
    else:
        reward20 = rangeReward(0, 20, myHistory, oppHistory)
        reward40 = rangeReward(20, 40, myHistory, oppHistory)
        if (reward20 > reward40):
            return defect
        else:
            return cooperate
        
# straight tabbed into this after typing func def
def main(num_of_iterations, num_of_strategies):
    if num_of_iterations:
        num_of_iterations = int(num_of_iterations)
    else:
        num_of_iterations = 2000
    if num_of_strategies:
        num_of_strategies = int(num_of_strategies)
    else:
        num_of_strategies = 8

if __name__ == "__main__":
    # take in the command line args ?
    # run iterations? and get them etc etc...
    # determine how to go down the list there 
    pass